//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaaSAdmin.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaaSAdminDbEntities : DbContext
    {
        public PaaSAdminDbEntities()
            : base("name=PaaSAdminDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaaSWebSites> PaaSWebSites { get; set; }
        public virtual DbSet<PaaSConfig> PaaSConfig { get; set; }
        public virtual DbSet<PaaSDeviceHealth> PaaSDeviceHealth { get; set; }
        public virtual DbSet<PaaSDeviceHealthApp> PaaSDeviceHealthApp { get; set; }
        public virtual DbSet<PaaSDeviceHealthCpu> PaaSDeviceHealthCpu { get; set; }
        public virtual DbSet<PaaSDeviceHealthDisk> PaaSDeviceHealthDisk { get; set; }
        public virtual DbSet<PaaSDeviceHealthMemory> PaaSDeviceHealthMemory { get; set; }
    }
}
