//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaaSAdmin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaaSDeviceHealthApp
    {
        public long PaaSDeviceHealthAppId { get; set; }
        public long PaaSDeviceHealthId { get; set; }
        public int PID { get; set; }
        public string ApplicationPool { get; set; }
        public decimal CpuUsagePercent { get; set; }
        public decimal MemoryUsageMB { get; set; }
    }
}
