//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaaSAdmin.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaaSWebSites
    {
        public long IISWebSitesId { get; set; }
        public string WebSiteName { get; set; }
        public string Product { get; set; }
        public int Port { get; set; }
        public string IP { get; set; }
        public string Domain { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string PhysicalPath { get; set; }
        public decimal MaxMemoryGB { get; set; }
        public int MaxInstance { get; set; }
        public int RecycleMinutes { get; set; }
        public string RuntimeVersion { get; set; }
        public bool IsEnable32Bit { get; set; }
    }
}
